// source: hub.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var result_pb = require('./result_pb.js');
goog.object.extend(proto, result_pb);
goog.exportSymbol('proto.pb.BoolValue', null, global);
goog.exportSymbol('proto.pb.InvertibleField', null, global);
goog.exportSymbol('proto.pb.RangeField', null, global);
goog.exportSymbol('proto.pb.RangeField.Op', null, global);
goog.exportSymbol('proto.pb.SearchRequest', null, global);
goog.exportSymbol('proto.pb.UInt32Value', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.InvertibleField = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pb.InvertibleField.repeatedFields_, null);
};
goog.inherits(proto.pb.InvertibleField, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.InvertibleField.displayName = 'proto.pb.InvertibleField';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.BoolValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.BoolValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.BoolValue.displayName = 'proto.pb.BoolValue';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.UInt32Value = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.UInt32Value, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.UInt32Value.displayName = 'proto.pb.UInt32Value';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.RangeField = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pb.RangeField.repeatedFields_, null);
};
goog.inherits(proto.pb.RangeField, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.RangeField.displayName = 'proto.pb.RangeField';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.SearchRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pb.SearchRequest.repeatedFields_, null);
};
goog.inherits(proto.pb.SearchRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.SearchRequest.displayName = 'proto.pb.SearchRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pb.InvertibleField.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.InvertibleField.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.InvertibleField.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.InvertibleField} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.InvertibleField.toObject = function(includeInstance, msg) {
  var f, obj = {
    invert: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    valueList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.InvertibleField}
 */
proto.pb.InvertibleField.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.InvertibleField;
  return proto.pb.InvertibleField.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.InvertibleField} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.InvertibleField}
 */
proto.pb.InvertibleField.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setInvert(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.InvertibleField.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.InvertibleField.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.InvertibleField} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.InvertibleField.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInvert();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getValueList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * optional bool invert = 1;
 * @return {boolean}
 */
proto.pb.InvertibleField.prototype.getInvert = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pb.InvertibleField} returns this
 */
proto.pb.InvertibleField.prototype.setInvert = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * repeated string value = 2;
 * @return {!Array<string>}
 */
proto.pb.InvertibleField.prototype.getValueList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pb.InvertibleField} returns this
 */
proto.pb.InvertibleField.prototype.setValueList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pb.InvertibleField} returns this
 */
proto.pb.InvertibleField.prototype.addValue = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.InvertibleField} returns this
 */
proto.pb.InvertibleField.prototype.clearValueList = function() {
  return this.setValueList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.BoolValue.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.BoolValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.BoolValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.BoolValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.BoolValue}
 */
proto.pb.BoolValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.BoolValue;
  return proto.pb.BoolValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.BoolValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.BoolValue}
 */
proto.pb.BoolValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.BoolValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.BoolValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.BoolValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.BoolValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool value = 1;
 * @return {boolean}
 */
proto.pb.BoolValue.prototype.getValue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pb.BoolValue} returns this
 */
proto.pb.BoolValue.prototype.setValue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.UInt32Value.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.UInt32Value.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.UInt32Value} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.UInt32Value.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.UInt32Value}
 */
proto.pb.UInt32Value.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.UInt32Value;
  return proto.pb.UInt32Value.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.UInt32Value} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.UInt32Value}
 */
proto.pb.UInt32Value.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.UInt32Value.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.UInt32Value.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.UInt32Value} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.UInt32Value.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
};


/**
 * optional uint32 value = 1;
 * @return {number}
 */
proto.pb.UInt32Value.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.UInt32Value} returns this
 */
proto.pb.UInt32Value.prototype.setValue = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pb.RangeField.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.RangeField.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.RangeField.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.RangeField} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.RangeField.toObject = function(includeInstance, msg) {
  var f, obj = {
    op: jspb.Message.getFieldWithDefault(msg, 1, 0),
    valueList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.RangeField}
 */
proto.pb.RangeField.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.RangeField;
  return proto.pb.RangeField.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.RangeField} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.RangeField}
 */
proto.pb.RangeField.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.pb.RangeField.Op} */ (reader.readEnum());
      msg.setOp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.RangeField.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.RangeField.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.RangeField} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.RangeField.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOp();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getValueList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.pb.RangeField.Op = {
  EQ: 0,
  LTE: 1,
  GTE: 2,
  LT: 3,
  GT: 4
};

/**
 * optional Op op = 1;
 * @return {!proto.pb.RangeField.Op}
 */
proto.pb.RangeField.prototype.getOp = function() {
  return /** @type {!proto.pb.RangeField.Op} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.pb.RangeField.Op} value
 * @return {!proto.pb.RangeField} returns this
 */
proto.pb.RangeField.prototype.setOp = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * repeated string value = 2;
 * @return {!Array<string>}
 */
proto.pb.RangeField.prototype.getValueList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pb.RangeField} returns this
 */
proto.pb.RangeField.prototype.setValueList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pb.RangeField} returns this
 */
proto.pb.RangeField.prototype.addValue = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.RangeField} returns this
 */
proto.pb.RangeField.prototype.clearValueList = function() {
  return this.setValueList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pb.SearchRequest.repeatedFields_ = [5,25,27,28,49,50,51,55,56];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.SearchRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.SearchRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.SearchRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SearchRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    claimId: (f = msg.getClaimId()) && proto.pb.InvertibleField.toObject(includeInstance, f),
    channelId: (f = msg.getChannelId()) && proto.pb.InvertibleField.toObject(includeInstance, f),
    text: jspb.Message.getFieldWithDefault(msg, 3, ""),
    limit: jspb.Message.getFieldWithDefault(msg, 4, 0),
    orderByList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    offset: jspb.Message.getFieldWithDefault(msg, 6, 0),
    isControlling: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    lastTakeOverHeight: jspb.Message.getFieldWithDefault(msg, 8, ""),
    name: jspb.Message.getFieldWithDefault(msg, 9, ""),
    normalizedName: jspb.Message.getFieldWithDefault(msg, 10, ""),
    txPosition: (f = msg.getTxPosition()) && proto.pb.RangeField.toObject(includeInstance, f),
    amount: (f = msg.getAmount()) && proto.pb.RangeField.toObject(includeInstance, f),
    timestamp: (f = msg.getTimestamp()) && proto.pb.RangeField.toObject(includeInstance, f),
    creationTimestamp: (f = msg.getCreationTimestamp()) && proto.pb.RangeField.toObject(includeInstance, f),
    height: (f = msg.getHeight()) && proto.pb.RangeField.toObject(includeInstance, f),
    creationHeight: (f = msg.getCreationHeight()) && proto.pb.RangeField.toObject(includeInstance, f),
    activationHeight: (f = msg.getActivationHeight()) && proto.pb.RangeField.toObject(includeInstance, f),
    expirationHeight: (f = msg.getExpirationHeight()) && proto.pb.RangeField.toObject(includeInstance, f),
    releaseTime: (f = msg.getReleaseTime()) && proto.pb.RangeField.toObject(includeInstance, f),
    shortUrl: jspb.Message.getFieldWithDefault(msg, 20, ""),
    canonicalUrl: jspb.Message.getFieldWithDefault(msg, 21, ""),
    title: jspb.Message.getFieldWithDefault(msg, 22, ""),
    author: jspb.Message.getFieldWithDefault(msg, 23, ""),
    description: jspb.Message.getFieldWithDefault(msg, 24, ""),
    claimTypeList: (f = jspb.Message.getRepeatedField(msg, 25)) == null ? undefined : f,
    repostCount: (f = msg.getRepostCount()) && proto.pb.RangeField.toObject(includeInstance, f),
    streamTypeList: (f = jspb.Message.getRepeatedField(msg, 27)) == null ? undefined : f,
    mediaTypeList: (f = jspb.Message.getRepeatedField(msg, 28)) == null ? undefined : f,
    feeAmount: (f = msg.getFeeAmount()) && proto.pb.RangeField.toObject(includeInstance, f),
    feeCurrency: jspb.Message.getFieldWithDefault(msg, 30, ""),
    duration: (f = msg.getDuration()) && proto.pb.RangeField.toObject(includeInstance, f),
    repostedClaimId: jspb.Message.getFieldWithDefault(msg, 32, ""),
    censorType: (f = msg.getCensorType()) && proto.pb.RangeField.toObject(includeInstance, f),
    claimsInChannel: jspb.Message.getFieldWithDefault(msg, 34, ""),
    channelJoin: (f = msg.getChannelJoin()) && proto.pb.RangeField.toObject(includeInstance, f),
    isSignatureValid: (f = msg.getIsSignatureValid()) && proto.pb.BoolValue.toObject(includeInstance, f),
    effectiveAmount: (f = msg.getEffectiveAmount()) && proto.pb.RangeField.toObject(includeInstance, f),
    supportAmount: (f = msg.getSupportAmount()) && proto.pb.RangeField.toObject(includeInstance, f),
    trendingScore: (f = msg.getTrendingScore()) && proto.pb.RangeField.toObject(includeInstance, f),
    txId: jspb.Message.getFieldWithDefault(msg, 43, ""),
    txNout: (f = msg.getTxNout()) && proto.pb.UInt32Value.toObject(includeInstance, f),
    signature: jspb.Message.getFieldWithDefault(msg, 45, ""),
    signatureDigest: jspb.Message.getFieldWithDefault(msg, 46, ""),
    publicKeyBytes: jspb.Message.getFieldWithDefault(msg, 47, ""),
    publicKeyId: jspb.Message.getFieldWithDefault(msg, 48, ""),
    anyTagsList: (f = jspb.Message.getRepeatedField(msg, 49)) == null ? undefined : f,
    allTagsList: (f = jspb.Message.getRepeatedField(msg, 50)) == null ? undefined : f,
    notTagsList: (f = jspb.Message.getRepeatedField(msg, 51)) == null ? undefined : f,
    hasChannelSignature: jspb.Message.getBooleanFieldWithDefault(msg, 52, false),
    hasSource: (f = msg.getHasSource()) && proto.pb.BoolValue.toObject(includeInstance, f),
    limitClaimsPerChannel: jspb.Message.getFieldWithDefault(msg, 54, 0),
    anyLanguagesList: (f = jspb.Message.getRepeatedField(msg, 55)) == null ? undefined : f,
    allLanguagesList: (f = jspb.Message.getRepeatedField(msg, 56)) == null ? undefined : f,
    removeDuplicates: jspb.Message.getBooleanFieldWithDefault(msg, 57, false),
    noTotals: jspb.Message.getBooleanFieldWithDefault(msg, 58, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.SearchRequest}
 */
proto.pb.SearchRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.SearchRequest;
  return proto.pb.SearchRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.SearchRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.SearchRequest}
 */
proto.pb.SearchRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.pb.InvertibleField;
      reader.readMessage(value,proto.pb.InvertibleField.deserializeBinaryFromReader);
      msg.setClaimId(value);
      break;
    case 2:
      var value = new proto.pb.InvertibleField;
      reader.readMessage(value,proto.pb.InvertibleField.deserializeBinaryFromReader);
      msg.setChannelId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLimit(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addOrderBy(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOffset(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsControlling(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastTakeOverHeight(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setNormalizedName(value);
      break;
    case 11:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setTxPosition(value);
      break;
    case 12:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setAmount(value);
      break;
    case 13:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 14:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setCreationTimestamp(value);
      break;
    case 15:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setHeight(value);
      break;
    case 16:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setCreationHeight(value);
      break;
    case 17:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setActivationHeight(value);
      break;
    case 18:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setExpirationHeight(value);
      break;
    case 19:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setReleaseTime(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setShortUrl(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setCanonicalUrl(value);
      break;
    case 22:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 23:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthor(value);
      break;
    case 24:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 25:
      var value = /** @type {string} */ (reader.readString());
      msg.addClaimType(value);
      break;
    case 26:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setRepostCount(value);
      break;
    case 27:
      var value = /** @type {string} */ (reader.readString());
      msg.addStreamType(value);
      break;
    case 28:
      var value = /** @type {string} */ (reader.readString());
      msg.addMediaType(value);
      break;
    case 29:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setFeeAmount(value);
      break;
    case 30:
      var value = /** @type {string} */ (reader.readString());
      msg.setFeeCurrency(value);
      break;
    case 31:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setDuration(value);
      break;
    case 32:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepostedClaimId(value);
      break;
    case 33:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setCensorType(value);
      break;
    case 34:
      var value = /** @type {string} */ (reader.readString());
      msg.setClaimsInChannel(value);
      break;
    case 35:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setChannelJoin(value);
      break;
    case 36:
      var value = new proto.pb.BoolValue;
      reader.readMessage(value,proto.pb.BoolValue.deserializeBinaryFromReader);
      msg.setIsSignatureValid(value);
      break;
    case 37:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setEffectiveAmount(value);
      break;
    case 38:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setSupportAmount(value);
      break;
    case 39:
      var value = new proto.pb.RangeField;
      reader.readMessage(value,proto.pb.RangeField.deserializeBinaryFromReader);
      msg.setTrendingScore(value);
      break;
    case 43:
      var value = /** @type {string} */ (reader.readString());
      msg.setTxId(value);
      break;
    case 44:
      var value = new proto.pb.UInt32Value;
      reader.readMessage(value,proto.pb.UInt32Value.deserializeBinaryFromReader);
      msg.setTxNout(value);
      break;
    case 45:
      var value = /** @type {string} */ (reader.readString());
      msg.setSignature(value);
      break;
    case 46:
      var value = /** @type {string} */ (reader.readString());
      msg.setSignatureDigest(value);
      break;
    case 47:
      var value = /** @type {string} */ (reader.readString());
      msg.setPublicKeyBytes(value);
      break;
    case 48:
      var value = /** @type {string} */ (reader.readString());
      msg.setPublicKeyId(value);
      break;
    case 49:
      var value = /** @type {string} */ (reader.readString());
      msg.addAnyTags(value);
      break;
    case 50:
      var value = /** @type {string} */ (reader.readString());
      msg.addAllTags(value);
      break;
    case 51:
      var value = /** @type {string} */ (reader.readString());
      msg.addNotTags(value);
      break;
    case 52:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasChannelSignature(value);
      break;
    case 53:
      var value = new proto.pb.BoolValue;
      reader.readMessage(value,proto.pb.BoolValue.deserializeBinaryFromReader);
      msg.setHasSource(value);
      break;
    case 54:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLimitClaimsPerChannel(value);
      break;
    case 55:
      var value = /** @type {string} */ (reader.readString());
      msg.addAnyLanguages(value);
      break;
    case 56:
      var value = /** @type {string} */ (reader.readString());
      msg.addAllLanguages(value);
      break;
    case 57:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRemoveDuplicates(value);
      break;
    case 58:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNoTotals(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.SearchRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.SearchRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.SearchRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SearchRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClaimId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.pb.InvertibleField.serializeBinaryToWriter
    );
  }
  f = message.getChannelId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.pb.InvertibleField.serializeBinaryToWriter
    );
  }
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLimit();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getOrderByList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getOffset();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getIsControlling();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getLastTakeOverHeight();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getNormalizedName();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getTxPosition();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getAmount();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getCreationTimestamp();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getHeight();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getCreationHeight();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getActivationHeight();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getExpirationHeight();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getReleaseTime();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getShortUrl();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getCanonicalUrl();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      22,
      f
    );
  }
  f = message.getAuthor();
  if (f.length > 0) {
    writer.writeString(
      23,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      24,
      f
    );
  }
  f = message.getClaimTypeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      25,
      f
    );
  }
  f = message.getRepostCount();
  if (f != null) {
    writer.writeMessage(
      26,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getStreamTypeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      27,
      f
    );
  }
  f = message.getMediaTypeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      28,
      f
    );
  }
  f = message.getFeeAmount();
  if (f != null) {
    writer.writeMessage(
      29,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getFeeCurrency();
  if (f.length > 0) {
    writer.writeString(
      30,
      f
    );
  }
  f = message.getDuration();
  if (f != null) {
    writer.writeMessage(
      31,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getRepostedClaimId();
  if (f.length > 0) {
    writer.writeString(
      32,
      f
    );
  }
  f = message.getCensorType();
  if (f != null) {
    writer.writeMessage(
      33,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getClaimsInChannel();
  if (f.length > 0) {
    writer.writeString(
      34,
      f
    );
  }
  f = message.getChannelJoin();
  if (f != null) {
    writer.writeMessage(
      35,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getIsSignatureValid();
  if (f != null) {
    writer.writeMessage(
      36,
      f,
      proto.pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getEffectiveAmount();
  if (f != null) {
    writer.writeMessage(
      37,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getSupportAmount();
  if (f != null) {
    writer.writeMessage(
      38,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getTrendingScore();
  if (f != null) {
    writer.writeMessage(
      39,
      f,
      proto.pb.RangeField.serializeBinaryToWriter
    );
  }
  f = message.getTxId();
  if (f.length > 0) {
    writer.writeString(
      43,
      f
    );
  }
  f = message.getTxNout();
  if (f != null) {
    writer.writeMessage(
      44,
      f,
      proto.pb.UInt32Value.serializeBinaryToWriter
    );
  }
  f = message.getSignature();
  if (f.length > 0) {
    writer.writeString(
      45,
      f
    );
  }
  f = message.getSignatureDigest();
  if (f.length > 0) {
    writer.writeString(
      46,
      f
    );
  }
  f = message.getPublicKeyBytes();
  if (f.length > 0) {
    writer.writeString(
      47,
      f
    );
  }
  f = message.getPublicKeyId();
  if (f.length > 0) {
    writer.writeString(
      48,
      f
    );
  }
  f = message.getAnyTagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      49,
      f
    );
  }
  f = message.getAllTagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      50,
      f
    );
  }
  f = message.getNotTagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      51,
      f
    );
  }
  f = message.getHasChannelSignature();
  if (f) {
    writer.writeBool(
      52,
      f
    );
  }
  f = message.getHasSource();
  if (f != null) {
    writer.writeMessage(
      53,
      f,
      proto.pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getLimitClaimsPerChannel();
  if (f !== 0) {
    writer.writeUint32(
      54,
      f
    );
  }
  f = message.getAnyLanguagesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      55,
      f
    );
  }
  f = message.getAllLanguagesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      56,
      f
    );
  }
  f = message.getRemoveDuplicates();
  if (f) {
    writer.writeBool(
      57,
      f
    );
  }
  f = message.getNoTotals();
  if (f) {
    writer.writeBool(
      58,
      f
    );
  }
};


/**
 * optional InvertibleField claim_id = 1;
 * @return {?proto.pb.InvertibleField}
 */
proto.pb.SearchRequest.prototype.getClaimId = function() {
  return /** @type{?proto.pb.InvertibleField} */ (
    jspb.Message.getWrapperField(this, proto.pb.InvertibleField, 1));
};


/**
 * @param {?proto.pb.InvertibleField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setClaimId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearClaimId = function() {
  return this.setClaimId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasClaimId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional InvertibleField channel_id = 2;
 * @return {?proto.pb.InvertibleField}
 */
proto.pb.SearchRequest.prototype.getChannelId = function() {
  return /** @type{?proto.pb.InvertibleField} */ (
    jspb.Message.getWrapperField(this, proto.pb.InvertibleField, 2));
};


/**
 * @param {?proto.pb.InvertibleField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setChannelId = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearChannelId = function() {
  return this.setChannelId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasChannelId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string text = 3;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint32 limit = 4;
 * @return {number}
 */
proto.pb.SearchRequest.prototype.getLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setLimit = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * repeated string order_by = 5;
 * @return {!Array<string>}
 */
proto.pb.SearchRequest.prototype.getOrderByList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setOrderByList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.addOrderBy = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearOrderByList = function() {
  return this.setOrderByList([]);
};


/**
 * optional uint32 offset = 6;
 * @return {number}
 */
proto.pb.SearchRequest.prototype.getOffset = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setOffset = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional bool is_controlling = 7;
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.getIsControlling = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setIsControlling = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional string last_take_over_height = 8;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getLastTakeOverHeight = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setLastTakeOverHeight = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string name = 9;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string normalized_name = 10;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getNormalizedName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setNormalizedName = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional RangeField tx_position = 11;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getTxPosition = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 11));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setTxPosition = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearTxPosition = function() {
  return this.setTxPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasTxPosition = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional RangeField amount = 12;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getAmount = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 12));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setAmount = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearAmount = function() {
  return this.setAmount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasAmount = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional RangeField timestamp = 13;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getTimestamp = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 13));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional RangeField creation_timestamp = 14;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getCreationTimestamp = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 14));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setCreationTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearCreationTimestamp = function() {
  return this.setCreationTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasCreationTimestamp = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional RangeField height = 15;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getHeight = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 15));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setHeight = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearHeight = function() {
  return this.setHeight(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasHeight = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional RangeField creation_height = 16;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getCreationHeight = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 16));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setCreationHeight = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearCreationHeight = function() {
  return this.setCreationHeight(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasCreationHeight = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional RangeField activation_height = 17;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getActivationHeight = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 17));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setActivationHeight = function(value) {
  return jspb.Message.setWrapperField(this, 17, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearActivationHeight = function() {
  return this.setActivationHeight(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasActivationHeight = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional RangeField expiration_height = 18;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getExpirationHeight = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 18));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setExpirationHeight = function(value) {
  return jspb.Message.setWrapperField(this, 18, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearExpirationHeight = function() {
  return this.setExpirationHeight(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasExpirationHeight = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional RangeField release_time = 19;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getReleaseTime = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 19));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setReleaseTime = function(value) {
  return jspb.Message.setWrapperField(this, 19, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearReleaseTime = function() {
  return this.setReleaseTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasReleaseTime = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional string short_url = 20;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getShortUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setShortUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 20, value);
};


/**
 * optional string canonical_url = 21;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getCanonicalUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setCanonicalUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};


/**
 * optional string title = 22;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 22, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 22, value);
};


/**
 * optional string author = 23;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getAuthor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 23, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setAuthor = function(value) {
  return jspb.Message.setProto3StringField(this, 23, value);
};


/**
 * optional string description = 24;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 24, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 24, value);
};


/**
 * repeated string claim_type = 25;
 * @return {!Array<string>}
 */
proto.pb.SearchRequest.prototype.getClaimTypeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 25));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setClaimTypeList = function(value) {
  return jspb.Message.setField(this, 25, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.addClaimType = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 25, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearClaimTypeList = function() {
  return this.setClaimTypeList([]);
};


/**
 * optional RangeField repost_count = 26;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getRepostCount = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 26));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setRepostCount = function(value) {
  return jspb.Message.setWrapperField(this, 26, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearRepostCount = function() {
  return this.setRepostCount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasRepostCount = function() {
  return jspb.Message.getField(this, 26) != null;
};


/**
 * repeated string stream_type = 27;
 * @return {!Array<string>}
 */
proto.pb.SearchRequest.prototype.getStreamTypeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 27));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setStreamTypeList = function(value) {
  return jspb.Message.setField(this, 27, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.addStreamType = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 27, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearStreamTypeList = function() {
  return this.setStreamTypeList([]);
};


/**
 * repeated string media_type = 28;
 * @return {!Array<string>}
 */
proto.pb.SearchRequest.prototype.getMediaTypeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 28));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setMediaTypeList = function(value) {
  return jspb.Message.setField(this, 28, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.addMediaType = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 28, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearMediaTypeList = function() {
  return this.setMediaTypeList([]);
};


/**
 * optional RangeField fee_amount = 29;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getFeeAmount = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 29));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setFeeAmount = function(value) {
  return jspb.Message.setWrapperField(this, 29, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearFeeAmount = function() {
  return this.setFeeAmount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasFeeAmount = function() {
  return jspb.Message.getField(this, 29) != null;
};


/**
 * optional string fee_currency = 30;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getFeeCurrency = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 30, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setFeeCurrency = function(value) {
  return jspb.Message.setProto3StringField(this, 30, value);
};


/**
 * optional RangeField duration = 31;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getDuration = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 31));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setDuration = function(value) {
  return jspb.Message.setWrapperField(this, 31, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearDuration = function() {
  return this.setDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasDuration = function() {
  return jspb.Message.getField(this, 31) != null;
};


/**
 * optional string reposted_claim_id = 32;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getRepostedClaimId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 32, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setRepostedClaimId = function(value) {
  return jspb.Message.setProto3StringField(this, 32, value);
};


/**
 * optional RangeField censor_type = 33;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getCensorType = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 33));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setCensorType = function(value) {
  return jspb.Message.setWrapperField(this, 33, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearCensorType = function() {
  return this.setCensorType(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasCensorType = function() {
  return jspb.Message.getField(this, 33) != null;
};


/**
 * optional string claims_in_channel = 34;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getClaimsInChannel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 34, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setClaimsInChannel = function(value) {
  return jspb.Message.setProto3StringField(this, 34, value);
};


/**
 * optional RangeField channel_join = 35;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getChannelJoin = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 35));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setChannelJoin = function(value) {
  return jspb.Message.setWrapperField(this, 35, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearChannelJoin = function() {
  return this.setChannelJoin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasChannelJoin = function() {
  return jspb.Message.getField(this, 35) != null;
};


/**
 * optional BoolValue is_signature_valid = 36;
 * @return {?proto.pb.BoolValue}
 */
proto.pb.SearchRequest.prototype.getIsSignatureValid = function() {
  return /** @type{?proto.pb.BoolValue} */ (
    jspb.Message.getWrapperField(this, proto.pb.BoolValue, 36));
};


/**
 * @param {?proto.pb.BoolValue|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setIsSignatureValid = function(value) {
  return jspb.Message.setWrapperField(this, 36, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearIsSignatureValid = function() {
  return this.setIsSignatureValid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasIsSignatureValid = function() {
  return jspb.Message.getField(this, 36) != null;
};


/**
 * optional RangeField effective_amount = 37;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getEffectiveAmount = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 37));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setEffectiveAmount = function(value) {
  return jspb.Message.setWrapperField(this, 37, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearEffectiveAmount = function() {
  return this.setEffectiveAmount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasEffectiveAmount = function() {
  return jspb.Message.getField(this, 37) != null;
};


/**
 * optional RangeField support_amount = 38;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getSupportAmount = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 38));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setSupportAmount = function(value) {
  return jspb.Message.setWrapperField(this, 38, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearSupportAmount = function() {
  return this.setSupportAmount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasSupportAmount = function() {
  return jspb.Message.getField(this, 38) != null;
};


/**
 * optional RangeField trending_score = 39;
 * @return {?proto.pb.RangeField}
 */
proto.pb.SearchRequest.prototype.getTrendingScore = function() {
  return /** @type{?proto.pb.RangeField} */ (
    jspb.Message.getWrapperField(this, proto.pb.RangeField, 39));
};


/**
 * @param {?proto.pb.RangeField|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setTrendingScore = function(value) {
  return jspb.Message.setWrapperField(this, 39, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearTrendingScore = function() {
  return this.setTrendingScore(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasTrendingScore = function() {
  return jspb.Message.getField(this, 39) != null;
};


/**
 * optional string tx_id = 43;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getTxId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 43, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setTxId = function(value) {
  return jspb.Message.setProto3StringField(this, 43, value);
};


/**
 * optional UInt32Value tx_nout = 44;
 * @return {?proto.pb.UInt32Value}
 */
proto.pb.SearchRequest.prototype.getTxNout = function() {
  return /** @type{?proto.pb.UInt32Value} */ (
    jspb.Message.getWrapperField(this, proto.pb.UInt32Value, 44));
};


/**
 * @param {?proto.pb.UInt32Value|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setTxNout = function(value) {
  return jspb.Message.setWrapperField(this, 44, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearTxNout = function() {
  return this.setTxNout(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasTxNout = function() {
  return jspb.Message.getField(this, 44) != null;
};


/**
 * optional string signature = 45;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getSignature = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 45, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setSignature = function(value) {
  return jspb.Message.setProto3StringField(this, 45, value);
};


/**
 * optional string signature_digest = 46;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getSignatureDigest = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 46, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setSignatureDigest = function(value) {
  return jspb.Message.setProto3StringField(this, 46, value);
};


/**
 * optional string public_key_bytes = 47;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getPublicKeyBytes = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 47, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setPublicKeyBytes = function(value) {
  return jspb.Message.setProto3StringField(this, 47, value);
};


/**
 * optional string public_key_id = 48;
 * @return {string}
 */
proto.pb.SearchRequest.prototype.getPublicKeyId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 48, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setPublicKeyId = function(value) {
  return jspb.Message.setProto3StringField(this, 48, value);
};


/**
 * repeated string any_tags = 49;
 * @return {!Array<string>}
 */
proto.pb.SearchRequest.prototype.getAnyTagsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 49));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setAnyTagsList = function(value) {
  return jspb.Message.setField(this, 49, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.addAnyTags = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 49, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearAnyTagsList = function() {
  return this.setAnyTagsList([]);
};


/**
 * repeated string all_tags = 50;
 * @return {!Array<string>}
 */
proto.pb.SearchRequest.prototype.getAllTagsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 50));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setAllTagsList = function(value) {
  return jspb.Message.setField(this, 50, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.addAllTags = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 50, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearAllTagsList = function() {
  return this.setAllTagsList([]);
};


/**
 * repeated string not_tags = 51;
 * @return {!Array<string>}
 */
proto.pb.SearchRequest.prototype.getNotTagsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 51));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setNotTagsList = function(value) {
  return jspb.Message.setField(this, 51, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.addNotTags = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 51, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearNotTagsList = function() {
  return this.setNotTagsList([]);
};


/**
 * optional bool has_channel_signature = 52;
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.getHasChannelSignature = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 52, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setHasChannelSignature = function(value) {
  return jspb.Message.setProto3BooleanField(this, 52, value);
};


/**
 * optional BoolValue has_source = 53;
 * @return {?proto.pb.BoolValue}
 */
proto.pb.SearchRequest.prototype.getHasSource = function() {
  return /** @type{?proto.pb.BoolValue} */ (
    jspb.Message.getWrapperField(this, proto.pb.BoolValue, 53));
};


/**
 * @param {?proto.pb.BoolValue|undefined} value
 * @return {!proto.pb.SearchRequest} returns this
*/
proto.pb.SearchRequest.prototype.setHasSource = function(value) {
  return jspb.Message.setWrapperField(this, 53, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearHasSource = function() {
  return this.setHasSource(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.hasHasSource = function() {
  return jspb.Message.getField(this, 53) != null;
};


/**
 * optional uint32 limit_claims_per_channel = 54;
 * @return {number}
 */
proto.pb.SearchRequest.prototype.getLimitClaimsPerChannel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 54, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setLimitClaimsPerChannel = function(value) {
  return jspb.Message.setProto3IntField(this, 54, value);
};


/**
 * repeated string any_languages = 55;
 * @return {!Array<string>}
 */
proto.pb.SearchRequest.prototype.getAnyLanguagesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 55));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setAnyLanguagesList = function(value) {
  return jspb.Message.setField(this, 55, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.addAnyLanguages = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 55, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearAnyLanguagesList = function() {
  return this.setAnyLanguagesList([]);
};


/**
 * repeated string all_languages = 56;
 * @return {!Array<string>}
 */
proto.pb.SearchRequest.prototype.getAllLanguagesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 56));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setAllLanguagesList = function(value) {
  return jspb.Message.setField(this, 56, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.addAllLanguages = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 56, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.clearAllLanguagesList = function() {
  return this.setAllLanguagesList([]);
};


/**
 * optional bool remove_duplicates = 57;
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.getRemoveDuplicates = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 57, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setRemoveDuplicates = function(value) {
  return jspb.Message.setProto3BooleanField(this, 57, value);
};


/**
 * optional bool no_totals = 58;
 * @return {boolean}
 */
proto.pb.SearchRequest.prototype.getNoTotals = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 58, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pb.SearchRequest} returns this
 */
proto.pb.SearchRequest.prototype.setNoTotals = function(value) {
  return jspb.Message.setProto3BooleanField(this, 58, value);
};


goog.object.extend(exports, proto.pb);
