// Code generated by protoc-gen-go. DO NOT EDIT.
// source: claim.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Claim_Type int32

const (
	Claim_STREAM  Claim_Type = 0
	Claim_CHANNEL Claim_Type = 1
)

var Claim_Type_name = map[int32]string{
	0: "STREAM",
	1: "CHANNEL",
}
var Claim_Type_value = map[string]int32{
	"STREAM":  0,
	"CHANNEL": 1,
}

func (x Claim_Type) String() string {
	return proto.EnumName(Claim_Type_name, int32(x))
}
func (Claim_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_claim_a3202fb9f6ae6b3e, []int{0, 0}
}

type Fee_Currency int32

const (
	Fee_LBC Fee_Currency = 0
	Fee_USD Fee_Currency = 1
)

var Fee_Currency_name = map[int32]string{
	0: "LBC",
	1: "USD",
}
var Fee_Currency_value = map[string]int32{
	"LBC": 0,
	"USD": 1,
}

func (x Fee_Currency) String() string {
	return proto.EnumName(Fee_Currency_name, int32(x))
}
func (Fee_Currency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_claim_a3202fb9f6ae6b3e, []int{3, 0}
}

type Claim struct {
	Type                 Claim_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Claim_Type" json:"type,omitempty"`
	Stream               *Stream    `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Channel              *Channel   `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Claim) Reset()         { *m = Claim{} }
func (m *Claim) String() string { return proto.CompactTextString(m) }
func (*Claim) ProtoMessage()    {}
func (*Claim) Descriptor() ([]byte, []int) {
	return fileDescriptor_claim_a3202fb9f6ae6b3e, []int{0}
}
func (m *Claim) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Claim.Unmarshal(m, b)
}
func (m *Claim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Claim.Marshal(b, m, deterministic)
}
func (dst *Claim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claim.Merge(dst, src)
}
func (m *Claim) XXX_Size() int {
	return xxx_messageInfo_Claim.Size(m)
}
func (m *Claim) XXX_DiscardUnknown() {
	xxx_messageInfo_Claim.DiscardUnknown(m)
}

var xxx_messageInfo_Claim proto.InternalMessageInfo

func (m *Claim) GetType() Claim_Type {
	if m != nil {
		return m.Type
	}
	return Claim_STREAM
}

func (m *Claim) GetStream() *Stream {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *Claim) GetChannel() *Channel {
	if m != nil {
		return m.Channel
	}
	return nil
}

type Channel struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ContactEmail         string   `protobuf:"bytes,4,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	HomepageUrl          string   `protobuf:"bytes,5,opt,name=homepage_url,json=homepageUrl,proto3" json:"homepage_url,omitempty"`
	Tags                 []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	ThumbnailUrl         string   `protobuf:"bytes,16,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	CoverUrl             string   `protobuf:"bytes,17,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_claim_a3202fb9f6ae6b3e, []int{1}
}
func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (dst *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(dst, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Channel) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Channel) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Channel) GetContactEmail() string {
	if m != nil {
		return m.ContactEmail
	}
	return ""
}

func (m *Channel) GetHomepageUrl() string {
	if m != nil {
		return m.HomepageUrl
	}
	return ""
}

func (m *Channel) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Channel) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

func (m *Channel) GetCoverUrl() string {
	if m != nil {
		return m.CoverUrl
	}
	return ""
}

type Stream struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Language             string   `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	MediaType            string   `protobuf:"bytes,6,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	License              string   `protobuf:"bytes,7,opt,name=license,proto3" json:"license,omitempty"`
	File                 *File    `protobuf:"bytes,8,opt,name=file,proto3" json:"file,omitempty"`
	Fee                  *Fee     `protobuf:"bytes,16,opt,name=fee,proto3" json:"fee,omitempty"`
	LicenseUrl           string   `protobuf:"bytes,17,opt,name=license_url,json=licenseUrl,proto3" json:"license_url,omitempty"`
	ThumbnailUrl         string   `protobuf:"bytes,18,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Duration             uint32   `protobuf:"varint,19,opt,name=duration,proto3" json:"duration,omitempty"`
	Tags                 []string `protobuf:"bytes,20,rep,name=tags,proto3" json:"tags,omitempty"`
	ReleaseTime          int64    `protobuf:"varint,21,opt,name=release_time,json=releaseTime,proto3" json:"release_time,omitempty"`
	Video                *Video   `protobuf:"bytes,22,opt,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_claim_a3202fb9f6ae6b3e, []int{2}
}
func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (dst *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(dst, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Stream) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Stream) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Stream) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Stream) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Stream) GetMediaType() string {
	if m != nil {
		return m.MediaType
	}
	return ""
}

func (m *Stream) GetLicense() string {
	if m != nil {
		return m.License
	}
	return ""
}

func (m *Stream) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Stream) GetFee() *Fee {
	if m != nil {
		return m.Fee
	}
	return nil
}

func (m *Stream) GetLicenseUrl() string {
	if m != nil {
		return m.LicenseUrl
	}
	return ""
}

func (m *Stream) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

func (m *Stream) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Stream) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Stream) GetReleaseTime() int64 {
	if m != nil {
		return m.ReleaseTime
	}
	return 0
}

func (m *Stream) GetVideo() *Video {
	if m != nil {
		return m.Video
	}
	return nil
}

type Fee struct {
	Currency             Fee_Currency `protobuf:"varint,1,opt,name=currency,proto3,enum=pb.Fee_Currency" json:"currency,omitempty"`
	Address              []byte       `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Amount               uint64       `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Fee) Reset()         { *m = Fee{} }
func (m *Fee) String() string { return proto.CompactTextString(m) }
func (*Fee) ProtoMessage()    {}
func (*Fee) Descriptor() ([]byte, []int) {
	return fileDescriptor_claim_a3202fb9f6ae6b3e, []int{3}
}
func (m *Fee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fee.Unmarshal(m, b)
}
func (m *Fee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fee.Marshal(b, m, deterministic)
}
func (dst *Fee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fee.Merge(dst, src)
}
func (m *Fee) XXX_Size() int {
	return xxx_messageInfo_Fee.Size(m)
}
func (m *Fee) XXX_DiscardUnknown() {
	xxx_messageInfo_Fee.DiscardUnknown(m)
}

var xxx_messageInfo_Fee proto.InternalMessageInfo

func (m *Fee) GetCurrency() Fee_Currency {
	if m != nil {
		return m.Currency
	}
	return Fee_LBC
}

func (m *Fee) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Fee) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 uint64   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_claim_a3202fb9f6ae6b3e, []int{4}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (dst *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(dst, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Video struct {
	Width                uint32   `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Video) Reset()         { *m = Video{} }
func (m *Video) String() string { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()    {}
func (*Video) Descriptor() ([]byte, []int) {
	return fileDescriptor_claim_a3202fb9f6ae6b3e, []int{5}
}
func (m *Video) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Video.Unmarshal(m, b)
}
func (m *Video) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Video.Marshal(b, m, deterministic)
}
func (dst *Video) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Video.Merge(dst, src)
}
func (m *Video) XXX_Size() int {
	return xxx_messageInfo_Video.Size(m)
}
func (m *Video) XXX_DiscardUnknown() {
	xxx_messageInfo_Video.DiscardUnknown(m)
}

var xxx_messageInfo_Video proto.InternalMessageInfo

func (m *Video) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Video) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*Claim)(nil), "pb.Claim")
	proto.RegisterType((*Channel)(nil), "pb.Channel")
	proto.RegisterType((*Stream)(nil), "pb.Stream")
	proto.RegisterType((*Fee)(nil), "pb.Fee")
	proto.RegisterType((*File)(nil), "pb.File")
	proto.RegisterType((*Video)(nil), "pb.Video")
	proto.RegisterEnum("pb.Claim_Type", Claim_Type_name, Claim_Type_value)
	proto.RegisterEnum("pb.Fee_Currency", Fee_Currency_name, Fee_Currency_value)
}

func init() { proto.RegisterFile("claim.proto", fileDescriptor_claim_a3202fb9f6ae6b3e) }

var fileDescriptor_claim_a3202fb9f6ae6b3e = []byte{
	// 624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xcd, 0x6e, 0xdb, 0x48,
	0x0c, 0xc7, 0xa3, 0x48, 0xb6, 0x25, 0xca, 0x0e, 0xbc, 0xb3, 0xd9, 0x40, 0x9b, 0x4d, 0x10, 0x47,
	0x8b, 0x02, 0x3e, 0x14, 0x3e, 0xa4, 0xe8, 0x03, 0xa4, 0x6e, 0x82, 0x02, 0x4d, 0x73, 0x98, 0x24,
	0xbd, 0x1a, 0x63, 0x89, 0xb1, 0x06, 0x1d, 0x7d, 0x40, 0x1a, 0xa5, 0x70, 0xaf, 0x7d, 0x88, 0xbe,
	0x48, 0x9f, 0xaf, 0x28, 0x86, 0x1a, 0xbb, 0x46, 0xd3, 0x1b, 0xf9, 0x23, 0x87, 0x26, 0xff, 0xa4,
	0x0c, 0x61, 0xa2, 0x84, 0xcc, 0x67, 0x55, 0x5d, 0xea, 0x92, 0xed, 0x57, 0xcb, 0xf8, 0x9b, 0x03,
	0xbd, 0xb9, 0x61, 0x2c, 0x06, 0x4f, 0xaf, 0x2b, 0x8c, 0x9c, 0x89, 0x33, 0x3d, 0xb8, 0x38, 0x98,
	0x55, 0xcb, 0x19, 0x05, 0x66, 0xf7, 0xeb, 0x0a, 0x39, 0xc5, 0x58, 0x0c, 0xfd, 0x46, 0xd7, 0x28,
	0xf2, 0x68, 0x7f, 0xe2, 0x4c, 0xc3, 0x0b, 0x30, 0x59, 0x77, 0x44, 0xb8, 0x8d, 0xb0, 0x17, 0x30,
	0x48, 0x32, 0x51, 0x14, 0xa8, 0x22, 0x97, 0x92, 0x42, 0x2a, 0xd5, 0x21, 0xbe, 0x89, 0xc5, 0x67,
	0xe0, 0x99, 0xc2, 0x0c, 0xa0, 0x7f, 0x77, 0xcf, 0xaf, 0x2e, 0x3f, 0x8c, 0xf7, 0x58, 0x08, 0x83,
	0xf9, 0xbb, 0xcb, 0xdb, 0xdb, 0xab, 0x9b, 0xb1, 0x13, 0xff, 0x70, 0x60, 0x60, 0x5f, 0xb1, 0x53,
	0x80, 0xaa, 0x5d, 0x2a, 0x99, 0x2c, 0x3e, 0xe1, 0x9a, 0x3a, 0x1c, 0xf2, 0xa0, 0x23, 0xef, 0x71,
	0xcd, 0x0e, 0xa1, 0xa7, 0xa5, 0x56, 0x48, 0x5d, 0x05, 0xbc, 0x73, 0xd8, 0x04, 0xc2, 0x14, 0x9b,
	0xa4, 0x96, 0x95, 0x96, 0x65, 0x41, 0xcd, 0x04, 0x7c, 0x17, 0xb1, 0xff, 0x61, 0x94, 0x94, 0x85,
	0x16, 0x89, 0x5e, 0x60, 0x2e, 0xa4, 0x8a, 0x3c, 0xca, 0x19, 0x5a, 0x78, 0x65, 0x18, 0x3b, 0x87,
	0x61, 0x56, 0xe6, 0x58, 0x89, 0x15, 0x2e, 0xda, 0x5a, 0x45, 0xbd, 0xae, 0xce, 0x86, 0x3d, 0xd4,
	0x8a, 0x31, 0xf0, 0xb4, 0x58, 0x35, 0x51, 0x7f, 0xe2, 0x4e, 0x03, 0x4e, 0xb6, 0xa9, 0xad, 0xb3,
	0x36, 0x5f, 0x16, 0x42, 0x2a, 0x7a, 0x37, 0xee, 0x6a, 0x6f, 0xa1, 0x79, 0xf8, 0x1f, 0x04, 0x49,
	0xf9, 0x84, 0x35, 0x25, 0xfc, 0x45, 0x09, 0x3e, 0x81, 0x87, 0x5a, 0xc5, 0xdf, 0x5d, 0xe8, 0x77,
	0xda, 0x9a, 0x1f, 0xc8, 0x44, 0x93, 0xd9, 0xc9, 0xc9, 0x66, 0xc7, 0xe0, 0x2b, 0x51, 0xac, 0x5a,
	0xb1, 0xda, 0xcc, 0xbd, 0xf5, 0x7f, 0x09, 0xe2, 0xee, 0x0a, 0x72, 0x04, 0x7d, 0xd1, 0xea, 0xac,
	0xac, 0xed, 0x9c, 0xd6, 0xfb, 0x5d, 0xa8, 0xde, 0x73, 0xa1, 0x4e, 0x01, 0x72, 0x4c, 0xa5, 0x58,
	0xd0, 0x85, 0xf4, 0x29, 0x21, 0x20, 0x42, 0x3b, 0x8c, 0x60, 0xa0, 0x64, 0x82, 0x45, 0x83, 0xd1,
	0x80, 0x62, 0x1b, 0x97, 0x9d, 0x80, 0xf7, 0x28, 0x15, 0x46, 0x3e, 0x5d, 0x82, 0x6f, 0x2e, 0xe1,
	0x5a, 0x2a, 0xe4, 0x44, 0xd9, 0xbf, 0xe0, 0x3e, 0x22, 0x92, 0x32, 0xe1, 0xc5, 0x80, 0x82, 0x88,
	0xdc, 0x30, 0x76, 0x06, 0xa1, 0xad, 0xb1, 0xa3, 0x0d, 0x58, 0x64, 0xa4, 0x7b, 0xa6, 0x2f, 0xfb,
	0x83, 0xbe, 0xc7, 0xe0, 0xa7, 0x6d, 0x2d, 0x68, 0xac, 0xbf, 0x27, 0xce, 0x74, 0xc4, 0xb7, 0xfe,
	0x76, 0x69, 0x87, 0x3b, 0x4b, 0x3b, 0x87, 0x61, 0x8d, 0x0a, 0x45, 0x83, 0x0b, 0x2d, 0x73, 0x8c,
	0xfe, 0x99, 0x38, 0x53, 0x97, 0x87, 0x96, 0xdd, 0xcb, 0xdc, 0x34, 0xd6, 0x7b, 0x92, 0x29, 0x96,
	0xd1, 0x11, 0x75, 0x1d, 0x98, 0xae, 0x3f, 0x1a, 0xc0, 0x3b, 0x1e, 0x7f, 0x75, 0xc0, 0xbd, 0x46,
	0x64, 0x2f, 0xc1, 0x4f, 0xda, 0xba, 0xc6, 0x22, 0x59, 0xdb, 0x6f, 0x6a, 0x6c, 0x27, 0x9c, 0xcd,
	0x2d, 0xe7, 0xdb, 0x0c, 0x23, 0xa1, 0x48, 0xd3, 0x1a, 0x9b, 0x86, 0x96, 0x39, 0xe4, 0x1b, 0x97,
	0xb6, 0x96, 0x97, 0x6d, 0xa1, 0x69, 0x99, 0x1e, 0xb7, 0x5e, 0x7c, 0x02, 0xfe, 0xa6, 0x0e, 0x1b,
	0x80, 0x7b, 0xf3, 0x66, 0x3e, 0xde, 0x33, 0xc6, 0xc3, 0xdd, 0xdb, 0xb1, 0x13, 0xcf, 0xc0, 0x33,
	0x42, 0x9b, 0x29, 0x0b, 0x91, 0x77, 0x5f, 0x75, 0xc0, 0xc9, 0x36, 0xac, 0x91, 0x5f, 0xba, 0xab,
	0xf1, 0x38, 0xd9, 0xf1, 0x6b, 0xe8, 0xd1, 0x14, 0xe6, 0x74, 0x3e, 0xcb, 0x54, 0x77, 0xb7, 0x36,
	0xe2, 0x9d, 0x63, 0x9a, 0xc8, 0x50, 0xae, 0x32, 0x4d, 0x8f, 0x46, 0xdc, 0x7a, 0xcb, 0x3e, 0xfd,
	0x93, 0xbc, 0xfa, 0x19, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xd7, 0xcb, 0x38, 0x58, 0x04, 0x00, 0x00,
}
